In [1]:
import tensorflow as tf 
print("Tensorflow Version: ", tf.__version__, "\n") #tensorflow version

Tensorflow Version:  2.12.0 



In [2]:
matrix = tf.constant(4, shape=(1,1), dtype=tf.float32) #tensor created
print(matrix, "\n")

tf.Tensor([[4.]], shape=(1, 1), dtype=float32) 



In [4]:
matrix = tf.eye(4)
print(matrix)

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)


In [5]:
matrix = tf.ones((5,9)) #5 rows and 9 columns
print(matrix)

tf.Tensor(
[[1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1.]], shape=(5, 9), dtype=float32)


In [10]:
matrix = tf.zeros((3,2)) #3 rows and 2 columns
print(matrix)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [11]:
matrix = tf.random.uniform((2,5), minval=0, maxval=3) #2 rows and 5 columns
print(matrix)

tf.Tensor(
[[0.14311838 1.9101949  2.915337   1.3083186  2.971901  ]
 [0.00608861 1.8075185  2.6327026  2.405031   1.5042661 ]], shape=(2, 5), dtype=float32)


In [12]:
matrix = tf.random.normal((2,5), mean=2, stddev=3)
print(tf.cast(matrix, dtype= tf.float64))

tf.Tensor(
[[2.89592886 0.21908259 2.69566536 2.70894074 0.29416609]
 [5.13021755 1.13485706 2.03527665 1.79345894 2.85054088]], shape=(2, 5), dtype=float64)


In [13]:
matrix = tf.range(start=0, limit=25, delta=3)
print(matrix)

tf.Tensor([ 0  3  6  9 12 15 18 21 24], shape=(9,), dtype=int32)


In [14]:
#Math Operations 
#Add
matrix_1 = tf.constant([1,5,9])
matrix_2 = tf.constant([1,2,12])
matrix_3 = tf.add(matrix_1, matrix_2)
print(matrix_3)
matrix_3 = matrix_1 + matrix_2
print(matrix_3)

tf.Tensor([ 2  7 21], shape=(3,), dtype=int32)
tf.Tensor([ 2  7 21], shape=(3,), dtype=int32)


In [15]:
#Subtract
matrix_1 = tf.constant([6,5,9])
matrix_2 = tf.constant([1,2,12])
matrix_3 = tf.subtract(matrix_1, matrix_2)
print(matrix_3)
matrix_3 = matrix_1 - matrix_2
print(matrix_3)

tf.Tensor([ 5  3 -3], shape=(3,), dtype=int32)
tf.Tensor([ 5  3 -3], shape=(3,), dtype=int32)


In [16]:
#Divide
matrix_1 = tf.constant([6,5,9])
matrix_2 = tf.constant([1,2,12])
matrix_3 = tf.divide(matrix_1, matrix_2)
print(matrix_3)
matrix_3 = matrix_1 / matrix_2
print(matrix_3)

tf.Tensor([6.   2.5  0.75], shape=(3,), dtype=float64)
tf.Tensor([6.   2.5  0.75], shape=(3,), dtype=float64)


In [17]:
#Multiply
matrix_1 = tf.constant([6,5,9])
matrix_2 = tf.constant([1,2,12])
matrix_3 = tf.multiply(matrix_1, matrix_2)
print(matrix_3)
matrix_3 = matrix_1 * matrix_2
print(matrix_3)

tf.Tensor([  6  10 108], shape=(3,), dtype=int32)
tf.Tensor([  6  10 108], shape=(3,), dtype=int32)
